---

- hosts: all
  become: true
  tasks:

  - name: installing apache2 package
    apt:
      name: apache2
      
  - name: update repository index
    apt:
      update_cache: yes
      state: latest

  - name: add php suport for apache
    apt:
       name: lib_apache2md php
       state: latest
